# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'shashankbarsin/bootcamp-demo:$(build.buildId)'

steps:
- script: docker build -t developer-camp:dev ./app
- task: Docker@1
  displayName: Container registry login
  inputs:
    command: login
    azureSubscriptionEndpoint: Demo123
    azureContainerRegistry: npazurebootcamp.azurecr.io
- script: docker build -t  npazurebootcamp.azurecr.io/$(imageName) ./app
- script: docker push npazurebootcamp.azurecr.io/$(imageName)